# Generated by Django 2.2.28 on 2023-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=256)),
            ],
        ),
    ]
