# Generated by Django 2.2.28 on 2023-02-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230203_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dsfsdfs',
        ),
        migrations.AddField(
            model_name='user',
            name='sddssd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
