# Generated by Django 2.2.28 on 2023-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_xdfds'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fsfsfs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
