# Generated by Django 2.2.28 on 2023-03-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_fsfsfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fsfsfs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sddssd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='xdfds',
        ),
    ]
